-- Human ticket numbers (TKT-0001, TKT-0002, …).
--
-- The web console derived its reference from the first four hex characters of
-- the ticket's uuid. Every seeded ticket's id starts with 0000, so all sixteen
-- read "TKT-0000" and could not be told apart or quoted. A counting column
-- gives each ticket a number people can say out loud.
--
-- Existing tickets are numbered in the order they were reported; new ones take
-- the next value from the identity sequence.

alter table public.tickets add column if not exists ticket_no bigint;

-- The backfill must not look like activity: ticket_touch would stamp every
-- ticket's updated_at with now() (so "Updated 5 days ago" became "just now"
-- across the board), and the audit trigger would log sixteen edits nobody made.
alter table public.tickets disable trigger ticket_touch_trg;
alter table public.tickets disable trigger trg_audit_tickets;

update public.tickets t
set ticket_no = s.n
from (select id, row_number() over (order by reported_at, id) as n from public.tickets) s
where s.id = t.id and t.ticket_no is null;

alter table public.tickets enable trigger ticket_touch_trg;
alter table public.tickets enable trigger trg_audit_tickets;

alter table public.tickets alter column ticket_no set not null;
alter table public.tickets alter column ticket_no add generated by default as identity;
select setval(
  pg_get_serial_sequence('public.tickets', 'ticket_no'),
  coalesce((select max(ticket_no) from public.tickets), 0) + 1,
  false
);
alter table public.tickets add constraint tickets_ticket_no_key unique (ticket_no);
